<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>RealmStudioX._3D</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.SharpDX.Assimp" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="3.1.2" />
    <PackageReference Include="log4net" Version="3.4.0" />
    <PackageReference Include="SkiaSharp" Version="4.151.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\Dialogs\" />
  </ItemGroup>

</Project>
